### ISSUE TITLE
Release for web3j 4.9.5

### ISSUE THREAD

**Issue by kczulko** [web3j/web3j-evm#90]
# _Issue_title_
I am missing web3jevm release for web3j 4.9.5

https://github.com/web3j/web3j-evm/blob/a40b044df37a0c3426dc24f71589b03327b3a8bc/build.gradle#L17

## _Issue_description_
I am missing web3j-evm release for web3j 4.9.5

## _Issue_context_
When using web3j in my project, I'd like to use the latest version together with web3j-evm

**Comment by NickSneo** [comment]
web3j-evm updated to use web3j v4.9.5
PR - https://github.com/web3j/web3j-evm/pull/91
